### ISSUE TITLE
About Left Recursion

### ISSUE THREAD

**Issue by diaozhongpu** [thomasyonug/deeplang#15]
Writing grammar, we often encounter left-recursive rules. As a recursive-descent parser, Anltr cannot process left-recursive rules (except single left-recursive rules). So we need to remove them using Elimination of Left Recursion.

**Comment by diaozhongpu** [comment]
Background Knowledge:
a left-recursive rules may look like:

```
 a   :   
    a   b
    |    b
;
```
As we can see, this rule for **a** calls **a** itself on the left-edge of a global alternative. And more specifically, it is a single left-recursive rule (SLR), and can be replaced by:

```
a   :   
     b+
;
```
Thus Anltr4 can automatically turn a SLR rule into a non-left-recursive rule.

However, things get complicated when left-recursion occurs over several rule invocations. An example would be:

```
a   :   
    b
    |    c
;
 
b   :   
    a
    |    c
;
```

to which the solution is not obvious.

**Comment by diaozhongpu** [comment]
What we described above is called mutually left-recursive rules (MLR). i.e. the rules of **exp** and **type** in our spec file (version 20200604)
So we need to fix them using elimination of left recursion.

**Comment by chinesebear** [comment]
Is it fixed in our latest spec ? @thomasyonug

**Comment by diaozhongpu** [comment]
In recent update on anltr files, we have fixed issues on mutual recursion.
