### ISSUE TITLE
Parser Tree与AST的区别，语法树的优化

### ISSUE THREAD

**Issue by chinesebear** [thomasyonug/deeplang#28]
https://stackoverflow.com/questions/5026517/whats-the-difference-between-parse-tree-and-ast

上面是stackoverflow上解释了解析树和抽象语法树的区别。

_The DSL book from Martin Fowler explains this nicely. The AST only contains all 'useful' elements that will be used for further processing, while the parse tree contains all the artifacts (spaces, brackets, ...) from the original document you parse_

这一段话说出了两者的区别之一。

**Comment by chinesebear** [comment]
In parse tree interior nodes are non terminal, leaves are terminal. In syntax tree interior nodes are operator, leaves are operands.

**Comment by chinesebear** [comment]
`x=1
y=2
3*(x+y)`

CST或者解析树：

![SyonV](https://user-images.githubusercontent.com/13201054/87222731-ee68f780-c3a8-11ea-8f76-dbfb4a10ff24.png)

AST抽象语法树：

![SyonV](https://user-images.githubusercontent.com/13201054/87222745-0e002000-c3a9-11ea-80db-33d3ac6d71f4.png)

**Comment by diaozhongpu** [comment]
我们将实现parse tree(CST)到AST的转换代码。藉此实现语法树化简

一些相关的讨论 #31 #32
